myfinance-web-netcore/Models/AccountPlanModel.cs
using System.Data;
using myfinance_web_netcore.Infra;

namespace myfinance_web_netcore.Models
{
    public class AccountPlanModel
    {
        public int? Id { get; set; }

        public string? Description { get; set; }

        public string? Type { get; set; }

        public void Insert()
        {
            List<AccountPlanModel> accountPlans = new List<AccountPlanModel>();
            DAL dalInstance = DAL.GetInstance;
            dalInstance.Connect();

            string sql = $"INSERT INTO ACCOUNT_PLANS(DESCRIPTION, TYPE) VALUES ('{Description}', '{Type}')";

            dalInstance.ExecuteCommand(sql);
            dalInstance.Disconnect();
        }

        public void Update(int? id)
        {
            DAL dalInstance = DAL.GetInstance;
            dalInstance.Connect();

            string sql = $"UPDATE ACCOUNT_PLANS SET DESCRIPTION = '{Description}', TYPE = '{Type}' WHERE ID = {id}";

            dalInstance.ExecuteCommand(sql);
            dalInstance.Disconnect();
        }

        public void Delete(int id)
        {
            DAL dal = DAL.GetInstance;
            dal.Connect();
            string sql = $"DELETE FROM ACCOUNT_PLANS WHERE ID = {id}";
            dal.ExecuteCommand(sql);
            dal.Disconnect();
        }

        public AccountPlanModel GetAccountPlanById(int? id)
        {
            DAL dalInstance = DAL.GetInstance;
            dalInstance.Connect();

            string sql = $"SELECT ID, DESCRIPTION, TYPE FROM ACCOUNT_PLANS WHERE ID = {id}";
            DataTable dataTable = dalInstance.Select(sql);

            AccountPlanModel accountPlan = new AccountPlanModel()
            {
                Id = int.Parse(dataTable.Rows[0]["ID"].ToString()),
                Description = dataTable.Rows[0]["DESCRIPTION"].ToString(),
                Type = dataTable.Rows[0]["TYPE"].ToString()
            };

            dalInstance.Disconnect();

            return accountPlan;
        }

        public List<AccountPlanModel> getAccountPlans()
        {
            List<AccountPlanModel> accountPlans = new List<AccountPlanModel>();
            DAL dalInstance = DAL.GetInstance;
            dalInstance.Connect();

            string sql = "SELECT ID, DESCRIPTION, TYPE FROM ACCOUNT_PLANS";
            DataTable dataTable = dalInstance.Select(sql);

            for (int i = 0; i < dataTable.Rows.Count; i++)
            {
                AccountPlanModel accountPlan = new AccountPlanModel()
                {
                    Id = int.Parse(dataTable.Rows[i]["ID"].ToString()),
                    Description = dataTable.Rows[i]["DESCRIPTION"].ToString(),
                    Type = dataTable.Rows[i]["TYPE"].ToString()
                };

                accountPlans.Add(accountPlan);
            }

            dalInstance.Disconnect();

            return accountPlans;
        }
    }
}

myfinance-web-netcore/Models/ErrorViewModel.cs
namespace myfinance_web_netcore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myfinance-web-netcore/Models/TransactionModel.cs
namespace myfinance_web_netcore.Models
{
  public class TransactionModel
  {
    public int? Id { get; set; }

    public DateTime Date { get; set; }

    public decimal Value { get; set; }

    public string? Type { get; set; }

    public string? History { get; set; }

    public int AccountPlanId { get; set; }

    public string? PaymentMethod { get; set; }
  }
}

myfinance-web-netcore/Controllers/AccountPlanController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers
{
    public class AccountPlanController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public AccountPlanController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<AccountPlanModel> accountPlans = new AccountPlanModel().getAccountPlans();
            ViewBag.List = accountPlans;
            return View();
        }

        [HttpGet]
        public IActionResult CreateAccountPlan(int? id)
        {
            if (id != null)
            {
                AccountPlanModel accountPlan = new AccountPlanModel().GetAccountPlanById(id);
                ViewBag.AccountPlan = accountPlan;
            }

            return View();
        }

        [HttpPost]
        public IActionResult CreateAccountPlan(AccountPlanModel form)
        {
            if (form.Id == null)
            {
                form.Insert();
            }
            else
            {
                form.Update(form.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DeleteAccountPlan(int id)
        {
            new AccountPlanModel().Delete(id);
            return RedirectToAction("Index");
        }
    }
}

myfinance-web-netcore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myfinance-web-netcore/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Domain;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ILogger<TransactionController> _logger;

        public TransactionController(ILogger<TransactionController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<TransactionModel> transactions = new Transaction().getTransactions();
            ViewBag.List = transactions;
            return View();
        }

        [HttpGet]
        public IActionResult CreateTransaction(int? id)
        {
            if (id != null)
            {
                TransactionModel transaction = new Transaction().GetTransactionById(id);
                ViewBag.Transaction = transaction;
            }
  
            ViewBag.AccountPlans = new AccountPlanModel().getAccountPlans();
            return View();
        }

        [HttpPost]
        public IActionResult CreateTransaction(TransactionModel form)
        {
            Transaction transaction = new Transaction();

             if (form.Id == null)
            {
                transaction.Insert(form);
            }
            else
            {
                transaction.Update(form);
            }
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DeleteTransaction(int id)
        {
            new Transaction().Delete(id);
            return RedirectToAction("Index");
        }
    }
}

myfinance-web-netcore/Views/AccountPlan/CreateAccountPlan.cshtml
@model myfinance_web_netcore.Models.AccountPlanModel

@{
    ViewData["Title"] = "Criar plano de conta";

    string vDescription = string.Empty;
    string vType = string.Empty;

    try {
        vDescription = @ViewBag.AccountPlan.Description;
        vType = @ViewBag.AccountPlan.Type;
    }
    catch {}
}

<h1>@ViewData["Title"]</h1>

<div>
    <form asp-controller="AccountPlan" asp-action="CreateAccountPlan">
        <input type="hidden" asp-for="Id"><br>
        
        <label>Descrição:</label><br>
        <input type="text" asp-for="Description" value="@vDescription"><br>

        <label>Tipo:</label><br>
        <input type="text" asp-for="Type" value="@vType"><br>

        <button type="submit" class="btn btn-block btn-success">Registrar</button>
    </form>
</div>

myfinance-web-netcore/Views/AccountPlan/Index.cshtml
@model myfinance_web_netcore.Models.AccountPlanModel
@{
    ViewData["Title"] = "Plano de contas"; 
}


<h3>Plano de contas</h3>
<hr>

<button type="button" class="btn btn-block btn-primary" onclick="createAccountPlan()">Criar plano de conta</button>

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>#</th>
        <th>Id</th>
        <th>Descrição</th>
        <th>Tipo</th>
    </tr>

    @{
        foreach (var accountPlan in (List<AccountPlanModel>)ViewBag.List)
        {
             <tr>
                <td><button type="button" class="btn btn-block btn-warning" onclick="editAccountPlan(@accountPlan.Id.ToString())">Editar</button></td>
                <td><button type="button" class="btn btn-block btn-danger" onclick="deleteAccountPlan(@accountPlan.Id.ToString())">Excluir</button></td>
                <td>@accountPlan.Id</td>
                <td>@accountPlan.Description</td>
                <td>@accountPlan.Type</td>
            </tr>
        }
    }
   
</table>

<script>
    function createAccountPlan() {
        window.location.href = '../AccountPlan/CreateAccountPlan';
    }

    function editAccountPlan(id) {
        window.location.href = '../AccountPlan/CreateAccountPlan/' + id;
    }

    function deleteAccountPlan(id) {
        window.location.href = '../AccountPlan/DeleteAccountPlan/' + id;
    }
</script>

myfinance-web-netcore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myfinance-web-netcore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_netcore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_netcore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_netcore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AccountPlan" asp-action="Index">Planos de contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - myfinance_web_netcore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

myfinance-web-netcore/Views/Transaction/CreateTransaction.cshtml
@using System.Globalization
@model myfinance_web_netcore.Models.TransactionModel

@{
    ViewData["Title"] = "Registrar transação financeira";

    int vId = 0;
    string vDate = string.Empty;
    string vValue = string.Empty;
    string vType = string.Empty;
    string vHistory = string.Empty;
    int vAccountPlanId = 0;
    string vPaymentMethod = string.Empty;

    try
    {
        vId = int.Parse(@ViewBag.Transaction.Id.ToString());
        vDate = DateTime.Parse(@ViewBag.Transaction.Date.ToString()).ToString("yyyy-MM-dd");
        vType = @ViewBag.Transaction.Type.ToString();
        vHistory = @ViewBag.Transaction.History.ToString();
        vAccountPlanId = int.Parse(@ViewBag.Transaction.AccountPlanId.ToString());
        vPaymentMethod = @ViewBag.Transaction.PaymentMethod.ToString();

        CultureInfo cultureInfo = CultureInfo.InvariantCulture;
        vValue = @ViewBag.Transaction.Value.ToString(cultureInfo);
    }
    catch { }
}

<h1>@ViewData["Title"]</h1>

<div>
    <form asp-controller="Transaction" asp-action="CreateTransaction">
        <input type="hidden" asp-for="Id"><br>

        <div class="form-group">
            <label>Data:</label>
            <input type="date" class="form-control" asp-for="Date" value="@vDate">
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Tipo:</label><br>
            <input id="transaction-type" type="text" class="form-control" asp-for="Type" value="@vType"><br>
        </div>

        <div class="form-group">
            <label>Valor:</label><br>
            <input type="text" class="form-control" asp-for="Value" step="0.01" value="@vValue">
            <span asp-validation-for="Value" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Histórico:</label><br>
            @Html.TextArea("History", vHistory, new { @class = "form-control" })
            <span asp-validation-for="History" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label>Plano de contas:</label>
            <select asp-for="AccountPlanId" class="form-control">
                @{
                    foreach (AccountPlanModel accountPlan in (List<AccountPlanModel>)ViewBag.AccountPlans)
                    {
                        if (accountPlan.Id == vAccountPlanId)
                        {
                            <option selected value="@accountPlan.Id">@accountPlan.Description</option>
                        }
                        else
                        {
                            <option value="@accountPlan.Id">@accountPlan.Description</option>
                        }
                    }
                }
            </select>
        </div>

        <div id="payment-method" class="form-group">
            <label>Tipo de pagamento:</label>
            <select asp-for="PaymentMethod" class="form-control">
                <option selected value="Dinheiro">Dinheiro</option>
                <option selected value="Débito">Débito</option>
                <option selected value="Crédito">Crédito</option>
                <option selected value="PIX">PIX</option>
                <option selected value="Boleto">Boleto</option>
            </select>
        </div>

        <button type="submit" class="btn btn-block btn-success">Registrar</button>
    </form>
</div>

<script>
    window.onload = function () {
        const type = document.getElementById('transaction-type').value;

        if (type.toUpperCase() === 'D')
            document.getElementById('payment-method').style.display = 'block';
    }

    document.getElementById('transaction-type').onchange = function (evt) {
        const displayType = evt.target.value.toUpperCase() === 'D' ? 'block' : 'none';

        document.getElementById('payment-method').style.display = displayType;
        document.getElementById('payment-method').value = null;
    }
</script>

<style>
    #payment-method {
        display: none;
    }
</style>

myfinance-web-netcore/Views/Transaction/Index.cshtml
@model myfinance_web_netcore.Models.TransactionModel
@{
    ViewData["Title"] = "Transações financeiras"; 
}

<h3>Transações financeiras</h3>
<hr>

<button type="button" class="btn btn-block btn-primary" onclick="createTransaction()">Criar transação</button>

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>#</th>
        <th>Id</th>
        <th>Data</th>
        <th>Valor</th>
        <th>Tipo</th>
        <th>Histórico</th>
        <th>Plano de conta</th>
    </tr>

    @{
        foreach (TransactionModel transaction in (List<TransactionModel>)ViewBag.List)
        {
             <tr>
                <td><button type="button" class="btn btn-block btn-warning" onclick="editTransaction(@transaction.Id.ToString())">Editar</button></td>
                <td><button type="button" class="btn btn-block btn-danger" onclick="deleteTransaction(@transaction.Id.ToString())">Excluir</button></td>
                <td>@transaction.Id</td>
                <td>@transaction.Date</td>
                <td>@transaction.Value</td>
                <td>@transaction.Type</td>
                <td>@transaction.History</td>
                <td>@transaction.AccountPlanId</td>
            </tr>
        }
    }
   
</table>

<script>
    function createTransaction() {
        window.location.href = '../Transaction/CreateTransaction';
    }

    function editTransaction(id) {
        window.location.href = '../Transaction/CreateTransaction/' + id;
    }

    function deleteTransaction(id) {
        window.location.href = '../Transaction/DeleteTransaction/' + id;
    }
</script>